services:
  bot:
    build: .
    container_name: work_auto_bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Europe/Kiev
      - DB_PATH=/app/data/bot_memory.db
      - SESSION_FILE=/app/data/session_name.session
    volumes:
      # Прокидываем директорию данных (для сохранения DB, -wal, -shm файлов и сессии)
      - ./data:/app/data
      # Прокидываем каталоги с файлами и логами
      - ./downloads:/app/downloads
      - ./output:/app/output
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Настройки ресурсов (опционально)
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
